add split
YdrMaster/gguf pull request #1
Opened 2024-07-18 09:06 UTC by qinyiqun

2024-07-18 11:38 UTC, YdrMaster requested changes

2024-07-18 11:38 UTC, YdrMaster commented on xtask/src/merge.rs
> +        // let mut writer: GGufWriter<File> = GGufWriter::new(out).unwrap();
这些注释掉的没用了吧

2024-07-18 11:38 UTC, YdrMaster commented on xtask/src/merge.rs
>                  (align as u64).to_le_bytes(),
确实是 u32，下面没改

2024-07-18 11:38 UTC, YdrMaster commented on ggus/src/metadata/mod.rs
> +    pub fn new(nbytes_: usize) -> Self {
new 一个带有生命周期的东西感觉有点奇怪，我再看看

2024-07-19 01:28 UTC, YdrMaster requested changes

2024-07-19 01:28 UTC, YdrMaster commented on xtask/src/split.rs
> +struct GGufFile<'a> {
我看这里有些代码和 merge 是重复的，把重复的部分抽出来放单独文件吧。现在代码是能跑的，这些修改可以在下一个 commit 里，不要 amend 了

2024-07-19 07:56 UTC, YdrMaster requested changes

2024-07-19 07:56 UTC, YdrMaster commented on xtask/src/gguf_file.rs
> +    pub(crate) fn get_header(&self) -> &GGufFileHeader {
一般属于小可见性对象的方法就不用写小的可见性了。反正 struct 都是 pub(crate)，方法直接写 pub 就行

2024-07-19 07:56 UTC, YdrMaster commented on xtask/src/gguf_file.rs
> +    pub(crate) fn get_header(&self) -> &GGufFileHeader {
以及为啥这些名字全都带个 get？不用带 get。

get 要么是 `get()`，要么是获得的东西有什么问题，比如是 Option 之类的

2024-07-19 07:59 UTC, YdrMaster requested changes

2024-07-19 07:59 UTC, YdrMaster commented on xtask/src/split.rs
> +        let input = PathBuf::from("/home/qinyiqun/gguf/xtask/src/test/rust/rust_ori.gguf");
这里不能出现你自己的机器上的路径啊😂可以用一个环境变量，或者就别这样写测试了，反正这是应用程序，直接可以跑着测

2024-07-19 08:05 UTC, YdrMaster requested changes

2024-07-19 08:05 UTC, YdrMaster commented on xtask/src/split.rs
> +fn split_path(path_prefix: &String, split_no: usize, split_count: usize) -> String {
这个函数定义出来只调用了一次，而且里面就一行的东西，没必要吧

2024-07-19 08:05 UTC, YdrMaster commented on xtask/src/split.rs
> +            let kvs = gguf.meta_kvs.kvs();
这个和你原来的意思一样吗：

```rust
for kv in gguf.meta_kvs.kvs() {
    if !matches!(
        kv.key(),
        LLM_KV_SPLIT_TENSORS_COUNT | LLM_KV_SPLIT_COUNT | LLM_KV_SPLIT_NO
    ) {
        writer
            .write_meta_kv(kv.key(), kv.ty(), kv.value_bytes())
            .unwrap();
    }
}
```

以及是不是应该直接在打开文件的时候检查，一个分片文件应该不能再分片了吧。

2024-07-19 08:17 UTC, qinyiqun commented on xtask/src/split.rs
> +            let kvs = gguf.meta_kvs.kvs();
这个应该不能在打开的时候检查的，split-merge之后llama.cpp是会把这几个kv放在merge后的文件里面的。

2024-07-19 08:21 UTC, qinyiqun commented on xtask/src/split.rs
> +        let input = PathBuf::from("/home/qinyiqun/gguf/xtask/src/test/rust/rust_ori.gguf");
这个是我自己测的。我之后就给删了hh

2024-07-19 11:15 UTC, YdrMaster commented on xtask/src/split.rs
> +            let kvs = gguf.meta_kvs.kvs();
嗯其实就是不用检查。规范里没有这几个 key，运行的时候也不需要，就当它们不存在就行。split 的时候不用加上，看见了也直接去掉就行。

2024-07-24 09:10 UTC, merged